version: '3'
services:
  mysqldb:
    image: mysql:8
    container_name: carbase-db
    restart: always
    networks:
      - carbase-mysql
    environment:
      MYSQL_USER: carbaseadmin
      MYSQL_PASSWORD: carbaseadmin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  api-gateway:
    image: pl.carsoft.carbase/carbase-api-gateway:0.0.1-SNAPSHOT
    ports:
      - "8084:8084"
    expose:
      - "8084"
    environment:
       SERVICE_CARSHARESERVICE_URL: http://carsharing-service:8083
       SERVICE_CARSERVICE_URL: http://car-service:8082
       SERVICE_PERSONSERVICE_URL: http://person-service:8081

  car-service:
    image: pl.carsoft.carbase/carbase-car-service:0.0.1-SNAPSHOT
    ports:
      - "8082:8082"
    expose:
      - "8082"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://carbase-db:3306/cardb?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: carbaseadmin
      SPRING_DATASOURCE_PASSWORD: carbaseadmin
    networks:
      - carbase-mysql

  person-service:
    image: pl.carsoft.carbase/carbase-person-service:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://carbase-db:3306/persondb?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: carbaseadmin
      SPRING_DATASOURCE_PASSWORD: carbaseadmin
    networks:
      - carbase-mysql

  carsharing-service:
    image: pl.carsoft.carbase/carbase-carsharing-service:0.0.1-SNAPSHOT
    ports:
      - "8083:8083"
    expose:
      - "8083"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://carbase-db:3306/carsharingdb?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: carbaseadmin
      SPRING_DATASOURCE_PASSWORD: carbaseadmin
      SERVICE_CARSERVICE_URL: http://car-service:8082
      SERVICE_PERSONSERVICE_URL: http://person-service:8081
    networks:
      - carbase-mysql

  carbase-vuejs:
    image: pl.carsoft.carbase/carbase-vuejs
      #container_name: carbase-vuejs
    volumes:
      - "/app"
      - "/app/node_modules"
    ports:
      - "8080:80"

networks:
  carbase-mysql:
